name: Tests
# on: push
on: [repository_dispatch, workflow_dispatch]
jobs:
  linting:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - '3.8'
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          # apt install -y adduser base-files bash bash-completion binutils-common:amd64 command-not-found coreutils cron-daemon-common debconf dhcpcd-base e2fsprogs fuse3 hdparm keyutils libattr1:amd64 libaudit-common libc-bin libc6:amd64 libmagic1t64:amd64 libmecab2:amd64 libpam-runtime libpython3.8-minimal:amd64 libpython3.8-stdlib:amd64 libsensors-config libtirpc-common locales login logrotate lsb-release ltrace man-db media-types multipath-tools nano netbase nftables openssl overlayroot procps python3.8-distutils python3.8-minimal rsyslog screen sudo tar tzdata ucf usb-modeswitch util-linux walinuxagent wget
          pip install black==24.8.0 importlib_metadata==8.5.0 opt_einsum==3.4.0 pyasn1_modules==0.4.2 pylint==2.15.10 uv==0.9.26
      - run: |
          python -m pip install --upgrade pip
          pip install pylint==2.15.10
          pip install black
      - run: |
          pip install .
      - run: |
          pylint --fail-under=10 deepface/
    env:
      ACCEPT_EULA: Y
      BOOTSTRAP_HASKELL_NONINTERACTIVE: '1'
      DEBIAN_FRONTEND: noninteractive
      DOTNET_MULTILEVEL_LOOKUP: '0'
      DOTNET_NOLOGO: '1'
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: '1'
      HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS: '3650'
      HOMEBREW_NO_AUTO_UPDATE: '1'
      HOSTNAME: pop-os
      ImageOS: ubuntu24
      ImageVersion: 20260111.209.1
      LC_CTYPE: C.UTF-8
      PLAT: linux-x86_64
      POWERSHELL_DISTRIBUTION_CHANNEL: GitHub-Actions-ubuntu24
      SHLVL: '1'
      TERM: xterm
      _PYI_LINUX_PROCESS_NAME: sawra
      _PYI_PARENT_PROCESS_LEVEL: '1'
  type-check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - '3.8'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          # apt install -y adduser base-files bash bash-completion binutils-common:amd64 command-not-found coreutils cron-daemon-common debconf dhcpcd-base e2fsprogs fuse3 hdparm keyutils libattr1:amd64 libaudit-common libc-bin libc6:amd64 libmagic1t64:amd64 libmecab2:amd64 libncursesw6:amd64 libpam-runtime libpython3.8-minimal:amd64 libpython3.8-stdlib:amd64 libsensors-config libtirpc-common locales login logrotate lsb-release ltrace man-db media-types multipath-tools nano netbase nftables openssl overlayroot procps python3.8-distutils python3.8-minimal rsyslog screen sudo tar tzdata ucf usb-modeswitch util-linux walinuxagent wget
          pip install black==24.8.0 importlib_metadata==8.5.0 mypy==1.14.1 opt_einsum==3.4.0 pyasn1_modules==0.4.2 pylint==2.15.10 uv==0.9.26
      - run: |
          python -m pip install --upgrade pip
      - run: |
          pip install mypy==1.14.1
          pip install .
      - run: |
          mypy deepface/
    env:
      ACCEPT_EULA: Y
      BOOTSTRAP_HASKELL_NONINTERACTIVE: '1'
      DEBIAN_FRONTEND: noninteractive
      DOTNET_MULTILEVEL_LOOKUP: '0'
      DOTNET_NOLOGO: '1'
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: '1'
      HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS: '3650'
      HOMEBREW_NO_AUTO_UPDATE: '1'
      HOSTNAME: pop-os
      ImageOS: ubuntu24
      ImageVersion: 20260111.209.1
      LC_CTYPE: C.UTF-8
      PLAT: linux-x86_64
      POWERSHELL_DISTRIBUTION_CHANNEL: GitHub-Actions-ubuntu24
      SHLVL: '1'
      TERM: xterm
      _PYI_LINUX_PROCESS_NAME: sawra
      _PYI_PARENT_PROCESS_LEVEL: '1'
  unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - '3.8'
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          # apt install -y adduser base-files bash bash-completion binutils-common:amd64 command-not-found coreutils cron-daemon-common debconf dhcpcd-base e2fsprogs fuse3 hdparm keyutils libacl1:amd64 libattr1:amd64 libaudit-common libbsd0:amd64 libc-bin libc6:amd64 libgl1:amd64 libglib2.0-0t64:amd64 libglvnd0:amd64 libglx0:amd64 libmagic1t64:amd64 libmd0:amd64 libmecab2:amd64 libpam-runtime libpcre2-8-0:amd64 libpython3.8-minimal:amd64 libpython3.8-stdlib:amd64 libselinux1:amd64 libsensors-config libtirpc-common libx11-6:amd64 libxau6:amd64 libxcb1:amd64 libxdmcp6:amd64 locales login logrotate lsb-release ltrace man-db media-types multipath-tools nano ncurses-base netbase nftables openssl overlayroot procps python3.8-distutils python3.8-minimal rsyslog screen sudo tar tzdata ucf usb-modeswitch util-linux walinuxagent wget
          pip install black==24.8.0 blinker==1.8.2 importlib_metadata==8.5.0 mypy==1.14.1 opt_einsum==3.4.0 pyasn1_modules==0.4.2 pylint==2.15.10 pytest==8.3.5 uv==0.9.26
      - run: |
          python -m pip install --upgrade pip
      - run: |
          pip install pytest
      - run: |
          pip install Werkzeug==2.0.2 flask==2.0.2
      - run: |
          pip install .
          cd tests/unit
      - run: |
          python -m pytest . -s --disable-warnings
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    # env:
    #   ACCEPT_EULA: Y
    #   BOOTSTRAP_HASKELL_NONINTERACTIVE: '1'
    #   DEBIAN_FRONTEND: noninteractive
    #   DEEPFACE_AUTH_TOKEN: some_token
    #   DEEPFACE_CONNECTION_DETAILS: some_connection_string
    #   DOTNET_MULTILEVEL_LOOKUP: '0'
    #   DOTNET_NOLOGO: '1'
    #   DOTNET_SKIP_FIRST_TIME_EXPERIENCE: '1'
    #   HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS: '3650'
    #   HOMEBREW_NO_AUTO_UPDATE: '1'
    #   HOSTNAME: pop-os
    #   ImageOS: ubuntu24
    #   ImageVersion: 20260111.209.1
    #   LC_CTYPE: C.UTF-8
    #   PLAT: linux-x86_64
    #   POWERSHELL_DISTRIBUTION_CHANNEL: GitHub-Actions-ubuntu24
    #   PYTEST_VERSION: 8.3.5
    #   SHLVL: '1'
    #   TERM: xterm
    #   TF2_BEHAVIOR: '1'
    #   TF_CPP_MIN_LOG_LEVEL: '3'
    #   TF_FORCE_GPU_ALLOW_GROWTH: 'true'
    #   TF_USE_LEGACY_KERAS: '1'
    #   TPU_ML_PLATFORM: Tensorflow
    #   _PYI_LINUX_PROCESS_NAME: sawra
    #   _PYI_PARENT_PROCESS_LEVEL: '1'
    timeout-minutes: 175.22530584732692
